select fuel_type_code_pudl as k, count(*) as n, count(distinct plant_id_eia) as plants, round(sum(net_generation_mwh)/1000000.0,2) as twh, round(sum(capacity_mw)/count(distinct report_date)/1000.0,2) as gw from t group by fuel_type_code_pudl order by n desc;
select fuel_type_code_pudl as k, count(*) as n, round(sum(net_generation_mwh)/1000000.0,2) as twh from t group by fuel_type_code_pudl order by n desc;
select ba_code as k, count(*) as n, round(sum(net_generation_mwh)/1000000.0,2) as twh from t group by ba_code order by twh desc limit 500;
select technology_description as k, count(*) as n, round(sum(net_generation_mwh)/1000000.0,2) as twh from t where state in ('TX','CA') and year between 2018 and 2024 group by technology_description order by twh desc limit 50;
select case when capacity_mw < 1 then 'a <1 MW' when capacity_mw < 10 then 'b 1-10' when capacity_mw < 100 then 'c 10-100' when capacity_mw < 500 then 'd 100-500' else 'e 500+' end as k, count(*) as n, round(sum(net_generation_mwh)/1000000.0,2) as twh from t group by case when capacity_mw < 1 then 'a <1 MW' when capacity_mw < 10 then 'b 1-10' when capacity_mw < 100 then 'c 10-100' when capacity_mw < 500 then 'd 100-500' else 'e 500+' end order by k;
select (year(generator_operating_date)/10)*10 as k, count(*) as n, round(sum(net_generation_mwh)/1000000.0,2) as twh from t group by (year(generator_operating_date)/10)*10 order by k;
select year as k, fuel_type_code_pudl as f, round(sum(net_generation_mwh)/1000000.0,3) as twh, round(sum(capacity_mw)/count(distinct report_date)/1000.0,3) as gw from t group by year, fuel_type_code_pudl order by k, f;
select year as k, fuel_type_code_pudl as f, round(sum(net_generation_mwh)/1000000.0,3) as twh, round(sum(capacity_mw)/12000.0,3) as gw from t group by year, fuel_type_code_pudl order by k, f;
select month as k, fuel_type_code_pudl as f, round(sum(net_generation_mwh)/1000000.0,3) as twh from t where year between 2015 and 2024 group by month, fuel_type_code_pudl order by k, f;
select plant_id_eia as p, latitude as lat, longitude as lon, fuel_type_code_pudl as f, round(sum(net_generation_mwh)/1000000.0,3) as twh, max(capacity_mw) as mw from t where latitude is not null group by plant_id_eia, latitude, longitude, fuel_type_code_pudl order by twh desc;
select count(*) as n from t where plant_name_eia like '%diablo%';
select count(*) as n from t where plant_name_eia like '%diablo%' or utility_name_eia like '%diablo%';
select count(*) as n from t where plant_name_eia like '%diablo%' or utility_name_eia like '%diablo%' or county like '%diablo%';
select count(*) as n, round(sum(net_generation_mwh)/1000000.0,1) as twh, round(avg(capacity_factor),3) as cf from t;
select count(distinct plant_id_eia) as plants from t;
select count(distinct report_date) as months from t;
select utility_name_eia as k, count(*) as n, round(sum(net_generation_mwh)/1000000.0,2) as twh from t group by utility_name_eia order by twh desc limit 200;
select report_date as k, round(sum(net_generation_mwh)/1000000.0,3) as twh from t where fuel_type_code_pudl = 'solar' group by report_date order by k;
select state as k, count(*) as n, round(sum(net_generation_mwh)/1000000.0,2) as twh from t where fuel_type_code_pudl in ('wind','solar') and year between 2020 and 2025 group by state order by twh desc;
select operational_status as k, count(*) as n from t where year = 2025 and month = 12 group by operational_status order by n desc;
select plant_name_eia as k, state as s, round(sum(net_generation_mwh)/1000000.0,3) as twh, max(capacity_mw) as mw from t where fuel_type_code_pudl = 'nuclear' group by plant_name_eia, state order by twh desc limit 20;
